### PR TITLE
add note about breaking changes

### PR DESCRIPTION
**Pull request by caleb15**
see https://github.com/CircleCI-Public/cimg-python/issues/16

I put it up top so it is easily visible for those transitioning to the new image.

### CODE REVIEW

**Comment by dsayling** [comment]
virtualenv is now included as a result of including pipenv - which is now the default recommended tool by the python packaging authority: https://packaging.python.org/guides/tool-recommendations/

**Comment by caleb15** [comment]
> virtualenv is now included as a result of including pipenv - which is now the default recommended tool by the python packaging authority: https://packaging.python.org/guides/tool-recommendations/

But I got a error when I tried to use it:

https://app.circleci.com/pipelines/github/15five/fifteen5/30227/workflows/8eef31fa-e4b4-42db-a2cc-34eeb90e28f1/jobs/186277

```
#!/bin/bash -eo pipefail
python -m venv venv
Error: [Errno 2] No such file or directory: '/home/circleci/project/venv/bin/python': '/home/circleci/project/venv/bin/python'

Exited with code exit status 1
CircleCI received exit code 1
```

Ci config:
```yml
.python-postgres: &python-postgres
  docker:
    - image: circleci/python:3.7-node # we only need node so image is same as python build image
    - image: circleci/postgres:11.5-alpine-ram
      environment:
        POSTGRES_USER: "fifteen5_dev"
        POSTGRES_DB: "fifteen5"

  environment:
    DJANGO_SETTINGS_MODULE: "ff.settings.ci"
    FF_DB_NAME: "fifteen5"
    FF_DB_USER: "fifteen5_dev"
    FF_DB_HOST: "localhost"
    FF_DB_PORT: "5432"

# later on...

  python-lint:
    <<: *python-postgres

    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libxmlsec1-dev xmlsec1

      - checkout
      - restore_cache:
          keys:
            - python-venv-{{ checksum "requirements/test.pip" }}
            - python-venv # if first doesnt hit cache we want to restore last existing cache

      - run:
          name: Create Virtual Environment
          command: python3 -m venv venv
```

**Comment by dsayling** [comment]
The change was deployed about 7 hours ago. Sadly, I can't see the CircleCI pipeline to see when it ran.

https://hub.docker.com/layers/cimg/python/3.7-node/images/sha256-8db05bcc725e7e04c66661a80cf6735efb43a0d78cefd30487fec88f08832c42?context=explore

Note the SHA below on the pull matches above and with layer 24 in the details above installing pipenv

`~|⇒ docker pull cimg/python:3.7-node          
3.7-node: Pulling from cimg/python
Digest: sha256:8db05bcc725e7e04c66661a80cf6735efb43a0d78cefd30487fec88f08832c42
Status: Image is up to date for cimg/python:3.7-node
docker.io/cimg/python:3.7-node
~|⇒ docker run -it cimg/python:3.7-node
circleci@bcd35b8298e5:~/project$ python -m venv venv
circleci@bcd35b8298e5:~/project$ pip freeze | grep virtual
virtualenv==20.0.25
virtualenv-clone==0.5.4
circleci@bcd35b8298e5:~/project$ pip freeze | grep env
pipenv==2020.6.2
virtualenv==20.0.25
virtualenv-clone==0.5.4`

**Comment by caleb15** [comment]
The failure I posted started 21 hours ago on 17:49:03 UTC, which sounds like it was after the deployment?

**Comment by dsayling** [comment]
I finally got a chance to look, your build is indeed using the latest image with venv, however the cache that you are restoring from likely has some broken links from the legacy image. 

```

The new image uses pyenv to manage the python versions which places the binary in a different location.

**Comment by caleb15** [comment]
I see, thanks. What is the new location?

I suppose this can be closed then.

**Pull request closed without merging**
