### PR TITLE
Publish v3.9.14. [release]

### PR DESCRIPTION
**Pull request by felicianotech**
For some reason v3.9.14 didn't publish in https://github.com/CircleCI-Public/cimg-python/pull/148 so running it again here.

### CODE REVIEW

**Review by JalexChen — APPROVED** [review]

**Comment by luzfcb** [comment]
It is interesting that even after this PR was merged, the tag was not yet created in docker hub 
https://hub.docker.com/r/cimg/python/tags?name=3.9.14 

Currently the CI run ended with failures on the main branch

**Comment by ralbertazzi** [comment]
Hi guys, any update on this? We're super eager to use Poetry 1.2, which should be part of this new release AFAIK 🙏

**Comment by felicianotech** [comment]
@luzfcb @ralbertazzi Apologies. This specific Python version was published twice and yet seemingly failed. We were finally able to work out the weird edge case here and it is published and available right now.

**Comment by felicianotech** [comment]
@ralbertazzi Just checked, it contains Poetry v1.2.1. 👍🏼

**Comment by tjmcs** [comment]
Thanks for working through that particular edge case for @ralbertazzi; @felicianotech

**Pull request merged**
