### PR TITLE
Publish v3.8.7. [release]

### PR DESCRIPTION
**Pull request by felicianotech**
Waiting on upstream to make this available before the build will pass.

### CODE REVIEW

**Comment by andrew-vts** [comment]
3.8.7 is now available upstream; can this be merged?

**Comment by felicianotech** [comment]
@andrew-vts It's not unfortunately. I just bumped the upstream PR: https://github.com/pyenv/pyenv/pull/1762

**Comment by andrew-vts** [comment]
Apologies, I thought that you had meant Python 3.8.7 itself (as in it was in rc at the time), rather than pyenv.

**Comment by felicianotech** [comment]
I've reached out to the PyEnv people directly on this now. Do to the nature of CircleCI Convenience Images, we can't wait like this for a release if this becomes a common delay. Will decide on a final solution soon.

**Review by dsayling — APPROVED** [review]

**Comment by felicianotech** [comment]
@andrew-vts No need to apologize. 🙂 Python v3.8.7 is now available on CircleCI.

**Pull request merged**
