### PR TITLE
Install pipenv in the images

### LINKED ISSUE #39: add pipenv to image
Since `pipenv` is pre-installed on the old Python images, and (I believe) is still the documented way to handle image caching (https://circleci.com/docs/2.0/language-python/#cache-dependencies), would it make sense to bake it into this image as well? The example documented here also won't work (`sudo pip install pipenv`), because `pip` isn't in root's path (https://github.com/CircleCI-Public/cimg-python/issues/19#issuecomment-645771562)

I tried switching from `circleci/python` to `cimg/python` and noticed that it failed because of it not being installed. While it's a relatively simple step to install it, it would be convenient to have it there.

### PR DESCRIPTION
**Pull request by dsayling**
Install pipenv into all the images

Resolves #39

### CODE REVIEW

**Comment by dsayling** [comment]
How do we decide what versions get updated and at what version? 
I guess its not really clear how those versions are chose and what that process is. I'll update the README too.

**Comment by felicianotech** [comment]
Since this is in beta, it'll be recent releases. Maybe going back 3 patch releases for each minor release that's still supported. Once this is GA, we don't update existing images. Changes are only for new images.

> I guess its not really clear how those versions are chose and what that process is.

The readme doesn't mention it because there's no updating images once this goes GA.

> I'll update the README too.

With what? Your readme update in this PR looks good.

**Comment by dsayling** [comment]
I made some tweaks to the contribution section to be clear. I generated the docker images myself at the latest versions to test - but didn't revert the changes as I didn't realize I needed to.

**Comment by wyardley** [comment]
Thanks all! Will give this a shot.

**Pull request merged**
